[project]
name = "strudel-team-brand-manager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "BozhenaSai", email = "bozhko.saiii@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
strudel-team-brand-manager = "strudel_team_brand_manager:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
